version: '3'
services:
  node-app:
    container_name: express-node-app-container
    image: imzzac/docker-learn
    ports:
      - 4000:4000
    env_file:
      - ./.env
    depends_on:
      - mongo
  mongo:
    image: mongo
    restart: always
    volumes:
      - mongo-db:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    depends_on:
      - mongo

  redis:
    image: redis

  nginx:
    image: nginx:stable-alpine
    ports:
      - "433:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - node-app


volumes:
  mongo-db: